ARDUINO_DIR = /usr/share/arduino
ARDUINO_PORT = /dev/ttyUSB*

BOARD_TAG = uno

include /usr/share/arduino/Arduino.mk

## avrdude -q -V -p atmega328p -D -c arduino -b 115200 -P /dev/ttyACM0 -U flash:w:build-uno/arduino.hex:i